<?php
/**
 * Candere Software
 *
 * @category Codilar
 * @package  CustomReports
 * @author Candere
 * @copyright Candere Pvt. Ltd. (https://www.candere.com/)
 */

$redeemInfo = [];
$redeemInfo = $block->getRedeeminfo();
$request = $block->getRequest();
?>

<div id="page:main-container" class="page-columns">
    <div class="admin__old">
        <div id="container" class="main-col">

            <div class="reports-content">
                <div class="entry-edit form-inline">
                    <form id="filter_form" action="" method="get" novalidate="novalidate" name="date-form">
                        <div></div>

                        <fieldset class="fieldset admin__fieldset " id="sales_report_base_fieldset">
                            <legend class="admin__legend legend">
                                <span></span>
                            </legend><br>

                            <div class="messages">
                            </div>

                            <div class="admin__field field field-show_order_statuses  with-note"
                                data-ui-id="grid-filter-form-fieldset-element-form-field-show-order-statuses">
                                <label class="label admin__field-label" for="sales_report_show_order_statuses"
                                data-ui-id="grid-filter-form-fieldset-element-select-show-order-statuses-label">
                                <span>Voucher Type</span></label>
                                <div class="admin__field-control control">
                                    <select id="sales_report_show_order_statuses" name="channel"
                                    class="select admin__control-select"
                                    data-ui-id="grid-filter-form-fieldset-element-select-show-order-statuses">
                                        <option value="" selected="selected">Select Type</option>
                                        <option value="b2b"
                                        <?php if (isset($request['channel']) && $request['channel'] == 'b2b') {
                                            echo 'selected';
                                        }?>>
                                        Kalyan B2B</option>
                                        <option value="qwikcilver"
                                        <?php if (isset($request['channel'])
                                            && $request['channel'] == 'qwikcilver') { echo 'selected'; } ?>>
                                        Kalyan Qwikcilver</option>
                                        <option value="gv"
                                        <?php if (isset($request['channel'])
                                            && $request['channel'] == 'gv') { echo 'selected'; } ?>>
                                            Candere Giftcard
                                        </option>
                                    </select>
                                </div>
                            </div>

                            <div class="admin__field field field-from admin__field-small"
                                data-ui-id="grid-filter-form-fieldset-element-form-field-from">
                                <label class="label admin__field-label" for="sales_report_from"
                                data-ui-id="grid-filter-form-fieldset-element-text-from-label">
                                <span>From</span></label>
                                <div class="admin__field-control control">
                                    <input name="from" id="sales_report_from"
                                    value="<?php if (!empty($request['from'])) {
                                        echo $block->escapeHtml($request['from']);
                                           } ?>"
                                    title="From" class="admin__control-text _required admin__control-text input-text "
                                    type="text" aria-required="true" autocomplete="off">
                                    <button type="button" class="ui-datepicker-trigger "></button>
                                </div>
                            </div>

                            <div class="admin__field field field-to admin__field-small"
                                data-ui-id="grid-filter-form-fieldset-element-form-field-to">
                                <label class="label admin__field-label" for="sales_report_to"
                                    data-ui-id="grid-filter-form-fieldset-element-text-to-label"><span>To</span></label>
                                <div class="admin__field-control control">
                                    <input name="to" id="sales_report_to"
                                    value="<?php if (!empty($request['to'])) {
                                        echo $block->escapeHtml($request['to']);
                                           } ?>"
                                    title="To" class="admin__control-text _required admin__control-text input-text "
                                    type="text" aria-required="true" autocomplete="off" onchange="TDate()">
                                    <button type="button" class="ui-datepicker-trigger v-middle"></button>

                                </div>
                            </div>

                            <div class="admin__field field field-to admin__field-small"
                                data-ui-id="grid-filter-form-fieldset-element-form-field-to">
                                <label class="label admin__field-label" for="voucher_code"
                                data-ui-id="grid-filter-form-fieldset-element-text-to-label">
                                    <span>Search by Voucher Code</span>
                                </label>
                                <div class="admin__field-control control">
                                    <input id="voucher_code" name="voucher_code"
                                        value="<?php if (isset($request['voucher_code'])
                                        && $request['voucher_code'] != "") {
                                               echo $block->escapeHtml($request['voucher_code']);
                                               }?>" title="Search by Voucher Code"
                                               class="admin__control-text input-text"
                                               type="text" aria-required="true" autocomplete="off">

                                </div>
                            </div>

                            <div class="admin__field field field-to admin__field-small"
                                data-ui-id="grid-filter-form-fieldset-element-form-field-to">
                                <label class="label admin__field-label" for="email_id"
                                    data-ui-id="grid-filter-form-fieldset-element-text-to-label">
                                    <span>Search by Email Id</span></label>
                                <div class="admin__field-control control">
                                    <input id="email_id" name="email_id"
                                        value="<?php if (isset($request['email_id']) && $request['email_id'] != "") {
                                            echo $block->escapeHtml($request['email_id']);
                                               } ?>" title="Search by Email ID" class="admin__control-text input-text "
                                               type="text" aria-required="true" autocomplete="off">
                                </div>
                            </div>


                            <div class="admin__field field">
                                <label class="label admin__field-label">

                                </label>
                                <div class="admin__field-control control">
                                    <button id="savelist" name="submit" class="primary" type="submit"
                                        onClick="checkDate()"><span>Submit</span></button>
                                    <button id="resetwalletreportform" name="resetwalletreportform" class="primary"
                                        type="button" onClick="resetVoucherForm()"><span>Reset</span></button>
                                </div>
                            </div>

                        </fieldset>

                    </form>
                </div>
                <script>
                    require(['mage/adminhtml/form'], function() {
                        new FormElementDependenceController({
                            "sales_report_order_statuses": {
                                "sales_report_show_order_statuses": {
                                    "values": ["1"],
                                    "negative": false
                                }
                            }
                        });
                    });
                </script>
            </div>
            <div id="id_9Mfvy9NOaFAFMy2gBBxZAjSkrEjWfGJs" data-grid-id="id_9Mfvy9NOaFAFMy2gBBxZAjSkrEjWfGJs">
                <div class="admin__data-grid-header admin__data-grid-toolbar">
                    <div class="admin__data-grid-header-row">
                        <div class="admin__data-grid-export">
                            <label class="admin__control-support-text" for="id_9Mfvy9NOaFAFMy2gBBxZAjSkrEjWfGJs_export">
                                Export to:</label>
                            <select name="id_9Mfvy9NOaFAFMy2gBBxZAjSkrEjWfGJs_export"
                                id="id_9Mfvy9NOaFAFMy2gBBxZAjSkrEjWfGJs_export" class="admin__control-select">
                        <option value="http://127.0.0.1/candere/admin/reports/report_sales/exportSalesExcel/
                            key/98fafb6fa25d1003c03d9af85149b030c41b45a2147f89e94a298752ab16e453/">
                            Excel XML
                        </option>
                            </select>

                            <a id="downloadLink" onclick="exportF(this)"><button>Export to excel</button></a>
                        </div>
                    </div>

                    <div class="admin__data-grid-header-row ">

                    </div>
                </div>

                <div class="admin__data-grid-wrap admin__data-grid-wrap-static">
                    <?php if (!empty($redeemInfo)) { ?>
                        <table class="data-grid wp-list-table widefat striped posts" id="pager" border="1">
                            <!-- <thead> -->
                            <tr>
                                <th class="data-grid-th col-period no-link col-period"><span>Sr. No.</span></th>
                                <th class="data-grid-th col-orders no-link col-orders_count">
                                    <span>Customer Email</span></th>
                                <th class="data-grid-th col-period no-link col-period"><span>Voucher Details</span></th>
                                <th class="data-grid-th col-period no-link col-period"><span>Amount</span></th>
                                <th class="data-grid-th col-period no-link col-period"><span>Voucher Code</span></th>
                                <th class="data-grid-th col-period no-link col-period">
                                    <span>Used against Order id</span></th>
                                <th class="data-grid-th col-period no-link col-period"><span>Amount used</span></th>
                                <th class="data-grid-th col-period no-link col-period"><span>Created Date</span></th>
                                <th class="data-grid-th col-period no-link col-period"><span>Expiry Date</span></th>
                            </tr>
                            </thead>

                            <tbody>

                                <?php $i = count($redeemInfo);
                                foreach ($redeemInfo as $key => $value) {

                                    $expiryDate = !empty($value["expire_date"]) ? date("Y-m-d", strtotime($value["expire_date"])) : '';
                                    $todayDate = date("Y-m-d");

                                    $customerEmail = null;
                                    if (isset($value['email']) && $value['email'] != "") {
                                        $customerEmail = $value['email'];
                                    } else {
                                        if (isset($value['customer_id'])) {
                                            $customerEmail = $block->getCustomerEmail($value['customer_id']);
                                        } else {
                                            $customerEmail = '';
                                        }
                                        
                                    }

                                    $refundedDate = null;
                                    if (isset($value['refunded_date']) && $value['refunded_date'] != "") {
                                        $refundedDate = date("d-m-Y", strtotime($value['refunded_date']));
                                    }

                                    $formatedExpiryDate = null;
                                    if (isset($value['expire_date']) && $value['expire_date'] != "") {
                                        $formatedExpiryDate = date("d-m-Y", strtotime($value['expire_date']));
                                    }

                                    $addedAmount = null;
                                    if (isset($value['added_amount']) && $value['added_amount'] != "" && $value['added_amount'] > 0) {
                                        $addedAmount = $value['added_amount'];
                                    }

                                    $refundedAmount = null;
                                    if (isset($value['refundable_amount']) && $value['refundable_amount'] != "" && $value['refundable_amount'] > 0) {
                                        $refundedAmount = $value['refundable_amount'];
                                    }

                                    $source = null;
                                    if (isset($value['source']) && $value['source'] != "") {
                                        $source = $value['source'];
                                    }
                                    if (isset($value['issuing_bank']) && $value['issuing_bank'] != "" && $value['issuing_bank'] == 'kalyan-online') {
                                        $source = 'Kalyan Signup';
                                    }
                                    ?>
                                    <tr>
                                        <td><?= $block->escapeHtml($i); ?></td>
                                        <td><?= $block->escapeHtml($customerEmail); ?></td>
                                        <td><?= $block->escapeHtml($source); ?></td>
                                        <td>
                                            <?php
                                            if ($addedAmount != "") {
                                                echo $block->escapeHtml($addedAmount);
                                            }
                                            if ($refundedAmount != "") {
                                                echo $block->escapeHtml($refundedAmount);
                                            }
                                            ?>
                                        </td>
                                        <td><?= !empty($value['coupon_no']) ? $block->escapeHtml($value['coupon_no']) : ''; ?></td>
                                        <td><?= !empty($value['order_number']) ? $block->escapeHtml($value['order_number']) : ''; ?></td>
                                        <td><?= !empty($value['is_used']) ? $block->escapeHtml($value['is_used']) : ''; ?></td>
                                        <td><?= !empty($refundedDate) ? $block->escapeHtml($refundedDate) : ''; ?></td>
                                        <td>
                                            <?php
                                            if ($expiryDate != "1970-01-01" && $todayDate >= $expiryDate) {
                                                echo $block->escapeHtml($formatedExpiryDate . " (Expired)");
                                            } else {
                                                echo $block->escapeHtml($formatedExpiryDate);
                                            }
                                            ?>
                                        </td>
                                    </tr>
                                    <?php $i--;
                                } ?>

                            </tbody>
                        </table>
                        <div id="pageNavPosition" class="pager-nav"></div>
                    <?php } else { ?>
                        <div class="data-grid-tr-no-data even">
                            <div class="empty-text">We couldn't find any records.</div>
                        </div>

                    <?php } ?>
                </div>
            </div>

            <script>
                var deps = [];
                deps.push('mage/adminhtml/grid');
                
                require(deps, function() {

                    //<![CDATA[
                    id_9Mfvy9NOaFAFMy2gBBxZAjSkrEjWfGJsJsObject = new varienGrid(
                        "id_9Mfvy9NOaFAFMy2gBBxZAjSkrEjWfGJs",
                        'http\u003A\u002F\u002F127.0.0.1\u002Fcandere\u002Fadmin\u002Freports\u002Freport_sales'
                        +'\u002Fsales\u002Fkey\u002F'
                        +'f6b4f573c129ff00cf7d18a1de6ee1cffd801f08b5a1ddf59b48303f4cada1de\u002F',
                        'page',
                        'sort',
                        'dir',
                        'filter'
                    );
                    id_9Mfvy9NOaFAFMy2gBBxZAjSkrEjWfGJsJsObject.useAjax = '';
                    id_9Mfvy9NOaFAFMy2gBBxZAjSkrEjWfGJsJsObject.rowClickCallback = openGridRow;

                    //]]>

                });
            </script>
            <script>
                require([
                    'jquery',
                    'mage/backend/validation',
                    "prototype"
                ], function(jQuery) {

                    //<![CDATA[
                    jQuery('#filter_form').mage('validation', {
                        errorClass: 'mage-error'
                    });

                    function filterFormSubmit() {
                        var filters = $$('#filter_form input', '#filter_form select'),
                            elements = [];

                        for (var i in filters) {
                            if (filters[i].value && filters[i].value.length && !filters[i].disabled) {
                                elements.push(filters[i]);
                            }
                        }

                        if (jQuery('#filter_form').valid()) {
                            setLocation('http\u003A\u002F\u002F127.0.0.1\u002Fcandere\u002Fadmin\u002Freports'
                            +'\u002Freport_sales\u002Fsales\u002Fkey'
                            +'\u002Ff6b4f573c129ff00cf7d18a1de6ee1cffd801f08b5a1ddf59b48303f4cada1de\u002Ffilter/' +
                                Base64.encode(Form.serializeElements(elements)) + '/'
                            );
                        }
                    }
                    //]]>
                    window.filterFormSubmit = filterFormSubmit;
                });
            </script>
        </div>
    </div>
</div>
<script>
    require(["jquery", "mage/calendar"], function($) {
        $("#sales_report_from").datepicker({
            showMonthAfterYear: false,
            dateFormat: 'mm/dd/yy',
            changeMonth: true,
            changeYear: true,
            yearRange: '2017:2030',
        })
    });

    require(["jquery", "mage/calendar"], function($) {
        $("#sales_report_to").datepicker({
            showMonthAfterYear: false,
            dateFormat: 'mm/dd/yy',
            changeMonth: true,
            changeYear: true,
            yearRange: '2017:2030',
        })
    });

    function checkDate() {
        var dateForm = document.forms['date-form'];
        var startDate = new Date(dateForm['from'].value);
        var endDate = new Date(dateForm['to'].value);
        var date = endDate - startDate;
        var diff = (date / 86400000);

        if (startDate >= endDate) {
            alert("Date FROM should be less than date TO");
        } else if ((startDate == '') && (endDate == '')) {
            alert("Please select Start Date and To date");
        }
    }

    function getPathFromUrl(url) {
        return url.split("?")[0];
    }

    function resetVoucherForm() {
        var resetpageurl = jQuery(location).attr("href");
        resetpageurl = getPathFromUrl(resetpageurl);
        window.location.href = resetpageurl;
    }

    function exportF(elem) {
        var table = document.getElementById("pager");
        var html = table.outerHTML;
        var url = 'data:application/vnd.ms-excel,' + escape(html); // Set your html table into url 
        elem.setAttribute("href", url);
        elem.setAttribute("download", "VoucherInfo.xls"); // Choose the file name
        return false;
    }
</script>

<script>
    /* eslint-env browser */
    /* global document */

    function Pager(tableName, itemsPerPage) {
        'use strict';

        this.tableName = tableName;
        this.itemsPerPage = itemsPerPage;
        this.currentPage = 1;
        this.pages = 0;
        this.inited = false;

        this.showRecords = function(from, to) {
            let rows = document.getElementById(tableName).rows;

            // i starts from 1 to skip table header row
            for (let i = 1; i < rows.length; i++) {
                if (i < from || i > to) {
                    rows[i].style.display = 'none';
                } else {
                    rows[i].style.display = '';
                }
            }
        };

        this.showPage = function(pageNumber) {
            if (!this.inited) {
                // Not initialized
                return;
            }

            let oldPageAnchor = document.getElementById('pg' + this.currentPage);
            oldPageAnchor.className = 'pg-normal';

            this.currentPage = pageNumber;
            let newPageAnchor = document.getElementById('pg' + this.currentPage);
            newPageAnchor.className = 'pg-selected';

            let from = (pageNumber - 1) * itemsPerPage + 1;
            let to = from + itemsPerPage - 1;
            this.showRecords(from, to);

            let pgNext = document.querySelector('.pg-next'),
                pgPrev = document.querySelector('.pg-prev');

            if (this.currentPage == this.pages) {
                pgNext.style.display = 'none';
            } else {
                pgNext.style.display = '';
            }

            if (this.currentPage === 1) {
                pgPrev.style.display = 'none';
            } else {
                pgPrev.style.display = '';
            }
        };

        this.prev = function() {
            if (this.currentPage > 1) {
                this.showPage(this.currentPage - 1);
            }
        };

        this.next = function() {
            if (this.currentPage < this.pages) {
                this.showPage(this.currentPage + 1);
            }
        };

        this.init = function() {
            let rows = document.getElementById(tableName).rows;
            let records = (rows.length - 1);

            this.pages = Math.ceil(records / itemsPerPage);
            this.inited = true;
        };

        this.showPageNav = function(pagerName, positionId) {
            if (!this.inited) {
                // Not initialized
                return;
            }

            let element = document.getElementById(positionId),
                pagerHtml = '<span onclick="' + pagerName + '.prev();" class="pg-normal pg-prev">&#171;</span>';

            for (let page = 1; page <= this.pages; page++) {
                pagerHtml += '<span id="pg' + page + '" class="pg-normal pg-next" onclick="' + pagerName
                    + '.showPage(' + page + ');">' + page + '</span>';
            }

            pagerHtml += '<span onclick="' + pagerName + '.next();" class="pg-normal">&#187;</span>';

            element.innerHTML = pagerHtml;
        };
    }
    let pager = new Pager('pager', 10);
    pager.init();
    pager.showPageNav('pager', 'pageNavPosition');
    pager.showPage(1);
</script>