<?php
/**
 * @var \Casio\LotterySale\Block\Draw $block
 * @var \Magento\Framework\Escaper $escaper
 */

use Casio\LotterySale\Model\LotteryApplication;
?>
<div class="casio-lottery-description">
<?php if ($block->getStatusLotterySale() == LotteryApplication::STATUS_APPLIED): ?>
    <p class="text-align-center"><?=  /* @noEscape */$escaper->escapeHtml(__('I have already applied.')) ?></p>
<?php else: ?>
    <p class="text-align-center"><?=  /* @noEscape */$escaper->escapeHtml(__('The application is closed.')) ?></p>
<?php endif; ?>
</div>
<div class="btns">
    <a class="btn btn-l is-submit" title="<?=  /* @noEscape */__('Continue shopping') ?>" href="<?=  /* @noEscape */$escaper->escapeUrl($block->getTopPageUrl()) ?>">
        <?=  /* @noEscape */__('Continue shopping') ?>
    </a>
</div>
